#!/usr/bin/env bash
# Display message Ctrl+c word "I hate the kill command"
# Display message before exit "Y U no love me?!"
echo $$ > /var/run/mypid.pid
trap 'echo I hate the kill command; rm /var/run/mypid.pid; exit' SIGTERM
trap 'echo Y U no love me?!' SIGINT
trap 'rm /var/run/mypid.pid; exit' SIGQUIT

while true; do
	echo To infinity and beyond
	sleep 2
done
